#support Chinese and English, use "zh" or "en". Notice that you must
#select a language and start the server first to see the language config file.
#支持中英文，zh和en。必须选定对应语言，启动后才会生成语言配置文件。
language: zh

#use Mysql as database
#使用mysql数据库
mysql-data-base:
  ip: 101.126.90.250
  port: 3306
  #type your own user and pwd
  #填写自己的user和 password
  user: WJZ
  password: 123456
  #不要有-等特殊符号，小写
  #do not use "-" or other special characters, use lowercase
  database-name: awesome_market
  #all table created by this plugin will use this prefix to prevent from conflicts
  #所有该插件创建的表的前缀，主要用于避免冲突
  table-prefix: am_